spring:
  datasource:
    url: jdbc:postgresql://dev-db:5432/aide_db
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: validate

logging:
  level:
    com.aide.service: DEBUG 