spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/aide_db
    username: postgres
    password: postgres
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

logging:
  level:
    com.aide.service: DEBUG 